### ISSUE TITLE
계정 삭제에서 에러 2개

### ISSUE THREAD

**Issue by RedChiken** [plzhelpus/SmartCabinet_Android#16]
* 로그인을 오래 놔두면 로그인 객체가 없어서 로그아웃이 안됨([사용자 재인증](https://firebase.google.com/docs/auth/android/manage-users#re-authenticate_a_user))
`06-01 08:30:05.327 8561-8561/org.plzhelpus.smartcabinet_android E/WindowManager: android.view.WindowLeaked: Activity org.plzhelpus.smartcabinet_android.main.NoGroupActivity has leaked window DecorView@b65ce58[] that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:417)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:331)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
        at android.app.Dialog.show(Dialog.java:316)
        at android.support.v7.app.AlertDialog$Builder.show(AlertDialog.java:1006)
        at org.plzhelpus.smartcabinet_android.main.NoGroupActivity$onCreate$4.onClick(NoGroupActivity.kt:117)
        at android.view.View.performClick(View.java:5610)
        at android.view.View$PerformClick.run(View.java:22265)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)`

* deleteUser가 호출이 안됨

**Comment by WraithKim** [comment]
deleteUser는 얼떨결에 해결됨;;;
