### ISSUE TITLE
Firebase 로그인 에러

### ISSUE THREAD

**Issue by lyuha** [plzhelpus/SmartCabinet_Android#6]
Nexus 5에서 로그인 시도 후 기기에 로그인되어 있는 계정으로 로그인하면 에러 발생

ErrorCode : 4 (`ErrorCodes.PROVIDER_ERROR`)
ErrorMessage: `com.firebase.ui.auth.FirebaseUiException: Code: 10, message: 10:`

<details>
<summary>Stack trace</summary>

```
E/AuthUiActivity: Sign-in error: 
                  com.firebase.ui.auth.FirebaseUiException: Code: 10, message: 10: 
                      at com.firebase.ui.auth.data.remote.GoogleSignInHandler.onActivityResult(GoogleSignInHandler.java:106)
                      at com.firebase.ui.auth.ui.idp.SingleSignInActivity.onActivityResult(SingleSignInActivity.java:115)
                      at android.app.Activity.dispatchActivityResult(Activity.java:6456)
                      at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
                      at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
                      at android.app.ActivityThread.-wrap16(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
</details>

**Comment by lyuha** [comment]
[Firebase Setup](https://firebase.google.com/docs/android/setup#use_the_firebase_assistant)

Use the firebase assistant 이후 Sign in 문제 해결.

위의 작업 후, firebase project에 sha-1키가 새로 등록되었다.

**Comment by WraithKim** [comment]
추가적으로 수동으로 서명하고 앱을 배포하는 경우, 해당 키를 파이어베이스 콘솔에 등록해야 됨. 
[Java에서 제공하는 keytool을 사용해서 자기가 만든 키의 sha1 보는 방법](https://developers.google.com/android/guides/client-auth)
[수동으로 앱 서명하는 방법](https://developer.android.com/studio/publish/app-signing)
